#!/usr/bin/python
import sys
import os
import shutil

def rmRf(pathToDir):
    fullPath = dir + '/' + pathToDir
    for dirFile in os.listdir(fullPath):
	if dirFile == '.htaccess':
            continue
	concratePath = fullPath + '/' + dirFile
	if os.path.isdir(concratePath):
            shutil.rmtree(concratePath)
	if os.path.isfile(concratePath):
            os.remove(concratePath)		

def clearCache():
    for path in pathList['cache']:
        rmRf(path)
    print 'Cache was cleared!'

def clearStatic():
    for path in pathList['pub']:
        rmRf(path)
    print 'Static was cleared!'

def clearGeneration():
    for path in pathList['generation']:
        rmRf(path)
    print 'Generation was cleared!'

def clearAll():
    clearCache()
    clearStatic()
    clearGeneration()

def cron():
    os.system(cronCommand)
    print 'Command "' + cronCommand + '" was ranned!'

def install():
    os.system(installCommand)
    print 'Command "' + installCommand + '" was ranned!'

def uninstall():
    os.system(uninstallCommand)
    print 'Command "' + uninstallCommand + '" was ranned!'

def reinstall():
    uninstall()
    install()    

def reindex():
    os.system(reindexCommand)
    print 'Command "' + reindexCommand + '" was ranned!'

def getProjectName():
    return os.path.split(os.getcwd())[1].split(".local")[0]

def run(argument):
    switcher = {
        "cache": clearCache,
        "static": clearStatic,
	"all": clearAll,
	"cron": cron,
	"reinstall": reinstall,
	"reindex": reindex
    }
    func = switcher.get(argument, lambda: "Incorrect command")
    return func()

cronCommand = "php -f bin/magento cron:run"
reindexCommand = "bin/magento indexer:reindex"
uninstallCommand = "php -f bin/magento setup:uninstall"
installCommand = 'php -f bin/magento setup:install --language="en_US" --timezone="Europe/Kiev" --currency="USD" --db-host="localhost" --db-name="' + getProjectName() + '" --db-user="root" --backend-frontname="admin" --base-url="http://' + getProjectName() + '.local" --admin-lastname="Admin" --admin-firstname="Admin" --admin-email="admin@example.com" --admin-user="admin" --admin-password="123123q"'

pathList = {'cache': ['var/cache', 'var/page_cache'], 'pub': ['pub/static'], 'generation': ['var/generation']}
dir = os.getcwd()
run(sys.argv[1])
